-- THE PORT'S OTHER GATE — the MOVE bot/WeightedBrain.lua plays, against the
-- JavaScript it was ported from.
--
--   luajit bot/tests/decisionVerify.lua [fixture]
--
-- bot/tests/panelEvalVerify.lua checks that the Lua port computes the same
-- feature VALUES as the JavaScript. That is necessary and it is not enough:
-- two evaluators can agree on every feature and still play different games,
-- because choosing is a SEARCH. Hold is candidate zero, ties leave the
-- incumbent standing, a beam must never drop hold, and at depth 2 a candidate
-- is worth the best of stopping there or any single reply. Every one of those
-- is a place two implementations drift apart while every feature still agrees.
--
-- So this fixture (bot/fixtures/decision_reference.json) records the MOVE, on
-- boards from real level-10 games, with the weight set the bot ships. It is
-- generated by
--     node games/the-game/ai/eval/export_decisions.js
-- in the GameCreator checkout, and carries the board, the cursor, the incoming
-- row, the rise clock, and what the JavaScript played there.
--
-- EVERY BOARD IS SETTLED. The exporter skips any board holding a cell
-- mid-animation, so the two sides can never disagree merely about what a
-- half-swapped panel is.
--
-- WHAT IT DOES NOT PIN. Both sides resolve their own cascades and price their
-- own payouts -- BoardSim here, LogicalBoard there -- because the two engines
-- ARE the same game and each resolve is already checked against its own
-- engine (bot/tests/boardSimVerify.lua 0/941, bot/tests/comboPartitionVerify
-- .lua on every legal swap of every real board). A disagreement here is
-- therefore a real disagreement about how to PLAY, which is the point.
--
-- EXCEPT PAST A GARBAGE BREAK, which is decided mechanically rather than by
-- judgement: the fixture says whether the JavaScript stopped at one
-- (`truncated`), and the brain says whether this side went through one
-- (brokeGarbage). Either way the two are no longer looking at the same board.
-- LogicalBoard cuts a cascade off at the first break, because the colours
-- that row turns into come off an RNG it may not read; BoardSim is handed
-- those colours by the engine it runs inside, and settles the board a tick
-- sooner than the engine does while it is at it. Those boards are counted and
-- reported, not required to match -- requiring it would pin this bot to the
-- other one's blind spot, or to a settling order neither engine performs.
--
-- IT COLLECTS. Reporting the first difference turns "where do they part
-- company?" into one question per run, and a run is long enough that that
-- matters.

package.path = "./?.lua;" .. package.path
require("bot.headlessBoot")
do local l = require("common.lib.logger"); l.setLogLevel(l.levels.ERROR) end
_G.loc = _G.loc or function(s) return tostring(s) end

local json = require("common.lib.dkjson")
local Match = require("common.engine.Match")
require("common.engine.checkMatches")
local GameModes = require("common.data.GameModes")
local LevelPresets = require("common.data.LevelPresets")
local GeneratorSource = require("common.engine.GeneratorSource")
local BoardSim = require("bot.BoardSim")
local WeightedBrain = require("bot.WeightedBrain")

local FIXTURE = arg[1] or "bot/fixtures/decision_reference.json"
local W = BoardSim.WIDTH

local f = io.open(FIXTURE, "r")
if not f then
  print("DECISION VERIFY FAILED: no fixture at " .. FIXTURE)
  print("  regenerate it: node games/the-game/ai/eval/export_decisions.js  (GameCreator repo)")
  os.exit(1)
end
local fixture = json.decode(f:read("*a"))
f:close()

-- A REAL level-10 stack, not a stub. EvalEarned asks the engine for stop time
-- rather than retyping the formula, and the formula branches on the level's
-- own stop settings -- so a stand-in with plausible numbers in it would be
-- testing the stand-in.
local mode = GameModes.getPreset(GameModes.IDs.ONE_PLAYER_ENDLESS)
local match = Match(GeneratorSource(1, true), mode.matchRules)
local stack = match:createStackWithSettings(LevelPresets.getModern(10), true, "controller")

-- The board in the shape BoardState.derive hands the brain: one cell per
-- square carrying colour, state code and the garbage flag. Everything here is
-- settled, so every state code is 0 (normal).
local function boardFrom(str, rows)
  local board = {}
  for r = 1, rows do
    local row = {}
    for c = 1, W do
      local ch = str:sub((r - 1) * W + c, (r - 1) * W + c)
      if ch == "." then row[c] = { c = 0, s = 0, isGarbage = false }
      elseif ch == "#" then row[c] = { c = 0, s = 0, isGarbage = true }
      else row[c] = { c = tonumber(ch), s = 0, isGarbage = false } end
    end
    board[r] = row
  end
  return board
end

-- maxColHeight the way BoardState.derive computes it: the highest row holding
-- a COLOUR. Garbage does not raise it, which is the same bound the JavaScript
-- reaches by refusing to enumerate a swap touching a garbage cell.
local function maxColHeight(board, rows)
  local top = 0
  for r = 1, rows do
    for c = 1, W do
      if board[r][c].c ~= 0 then top = r; break end
    end
  end
  return top
end

local fx = fixture
local profile = {
  weights = fx.weights,
  depth = fx.depth, beam = fx.beam,
  density = fx.density, rise = fx.rise, reaction = fx.reaction,
}
print(string.format("fixture: %s   depth %d  beam %d  rise %s  density %s",
  tostring(fx.profile), fx.depth or 1, fx.beam or 0,
  fx.rise and "on" or "off", fx.density and "on" or "off"))
print(string.format("decisions: %d", #fx.decisions))

local brain = WeightedBrain.new({ profile = profile })

local agreed, failures, kinds = 0, {}, {}
local strict, blind, blindDiff, jsStopped = 0, 0, 0, 0
for i = 1, #fx.decisions do
  local d = fx.decisions[i]
  local rows = d.rows
  local board = boardFrom(d.grid, rows)
  local clock = d.clock or {}
  local state = {
    board = board, width = W, rows = rows, height = rows,
    cursor = d.cursor,
    maxColHeight = maxColHeight(board, rows),
    displacement = clock.displacement,
    riseTimer = clock.riseTimer,
    pixelFrames = clock.pixelFrames,
    stopTime = clock.stopTime or 0,
    nextRow = d.nextRow,
  }

  local got = brain:decide(state, stack, nil)
  -- A BOARD IS REQUIRED TO MATCH ONLY WHERE NEITHER SIDE LOOKED PAST A
  -- GARBAGE BREAK. `truncated` is the JavaScript saying it stopped at one;
  -- brokeGarbage is this side saying it went through one.
  local sameView = not (d.truncated or brain.brokeGarbage)
  local gotKind = (got.type == "SWAP") and "swap" or "hold"
  local wantKind = d.kind

  local ok
  if gotKind ~= wantKind then ok = false
  elseif wantKind ~= "swap" then ok = true
  else ok = (got.pos[1] == d.move[1] and got.pos[2] == d.move[2]) end

  if sameView then strict = strict + 1 else blind = blind + 1 end
  if d.truncated then jsStopped = jsStopped + 1 end

  if ok then
    agreed = agreed + 1
  elseif not sameView then
    blindDiff = blindDiff + 1
  else
    local key = wantKind .. " -> " .. gotKind
    kinds[key] = (kinds[key] or 0) + 1
    if #failures < 20 then
      local wantStr = wantKind == "swap"
          and string.format("swap r%d c%d", d.move[1], d.move[2]) or wantKind
      local gotStr = gotKind == "swap"
          and string.format("swap r%d c%d", got.pos[1], got.pos[2]) or gotKind
      failures[#failures + 1] = string.format("  %-8s  js=%-14s lua=%s", d.at, wantStr, gotStr)
    end
  end
end

print(string.format("agreed on %d / %d decisions", agreed, #fx.decisions))
print(string.format("  %d required to match; %d reached a garbage break, where the two " ..
  "stop seeing one board (%d of those differ)", strict, blind, blindDiff))
print(string.format("  of those %d, the JavaScript stopped at the break on %d and this side " ..
  "went through one on %d", blind, jsStopped, blind - jsStopped))

if next(kinds) == nil then
  print("DECISION VERIFY OK: the Lua brain plays the move the JavaScript plays, on every " ..
        "board where the two can see the same thing.")
  os.exit(0)
end

print("")
print("DECISION VERIFY FAILED -- differences by kind:")
local keys = {}
for k in pairs(kinds) do keys[#keys + 1] = k end
table.sort(keys, function(a, b) return kinds[a] > kinds[b] end)
for _, k in ipairs(keys) do print(string.format("  %-20s %4d", k, kinds[k])) end
print("")
print("first differences:")
for _, line in ipairs(failures) do print(line) end
os.exit(1)
