-- THE PORT'S GATE — bot/PanelEval.lua against the JavaScript it was ported from.
--
--   luajit bot/tests/panelEvalVerify.lua [fixture]
--
-- PanelEval is a second implementation of rules that already exist in the
-- GameCreator repo (games/the-game/ai/eval/features.js). That is the shape of
-- work that goes wrong invisibly: both copies look fine, neither is obviously
-- stale, and the drift only shows up as a bot that plays slightly worse than it
-- used to for reasons nobody can point at. So the port is not reviewed, it is
-- CHECKED, on 393 boards the shipped bot actually sat on while playing the real
-- engine at level 10 — never hand-built, per that repo's standing rule.
--
-- The fixture (bot/fixtures/paneleval_reference.json) is generated by
--     node games/the-game/ai/eval/export_reference.js
-- in the GameCreator checkout, and carries, per board: the grid, what a move
-- paid (chainLength, comboSizes, garbageSent, ...), and every feature's value
-- as the JavaScript computed it.
--
-- EARNED IS DATA, NOT RECOMPUTED. The two languages resolve cascades with
-- different code — LogicalBoard there, BoardSim here — each already verified
-- against its own engine. Feeding both the same earned numbers means a
-- disagreement is a FEATURE bug rather than a resolve bug wearing its clothes.
--
-- THE FOUR LOOKAHEAD FEATURES ARE THE EXCEPTION, ON PURPOSE. matchPotential,
-- chainPotential, comboPotential and staircaseReady ask what a swap would do,
-- so they run both resolves against each other, on every board, for free. If
-- those disagree the two simulations disagree, and that is worth finding here
-- rather than in a match.
--
-- IT COLLECTS. A loop over N boards that throws on the first failure turns
-- "which features are wrong?" into one question per run, and this run takes
-- long enough that that matters. Every mismatch is gathered and the whole list
-- is reported at the end, grouped by feature.

package.path = "./?.lua;" .. package.path
require("bot.headlessBoot")

local json = require("common.lib.dkjson")
local PanelEval = require("bot.PanelEval")
local EvalPlan = require("bot.EvalPlan")
local BoardSim = require("bot.BoardSim")

local FIXTURE = arg[1] or "bot/fixtures/paneleval_reference.json"
local W = BoardSim.WIDTH

local f = io.open(FIXTURE, "r")
if not f then
  print("PANELEVAL VERIFY FAILED: no fixture at " .. FIXTURE)
  print("  regenerate it: node games/the-game/ai/eval/export_reference.js  (GameCreator repo)")
  os.exit(1)
end
local fixture = json.decode(f:read("*a"))
f:close()

print("fixture: " .. tostring(fixture.source))
print("boards:  " .. #fixture.boards .. "   features: " .. #fixture.features)

-- A PanelEval grid straight from the fixture (already in PanelEval's dialect),
-- and the BoardSim grid the plan needs, which is the same board in the other
-- dialect. Both are built from the SAME flat list, so the plan can never be
-- looking at a different board than the features are.
local H = fixture.height
local function gridsFrom(flat)
  local eval, sim = {}, {}
  for r = 1, H do
    local er, sr = {}, {}
    for c = 1, W do
      local v = flat[(r - 1) * W + c]
      er[c] = v
      -- inverse of EvalPlan.toEval. -1 (busy) has no BoardSim equivalent that
      -- is both immovable and unmatchable except RESOLVING, which is exactly
      -- what it means: a cell that is occupied and is not material.
      if v == 0 then sr[c] = 0
      elseif v == -2 then sr[c] = BoardSim.GARBAGE
      elseif v == -1 then sr[c] = BoardSim.RESOLVING
      else sr[c] = v end
    end
    eval[r] = er; sim[r] = sr
  end
  return eval, sim
end

-- Floating-point features (colourVariance, maxHeight, fillRatio, flatTop,
-- travelCost) cannot be compared for equality across two languages' printf and
-- JSON round-trips. 1e-9 is far tighter than any real disagreement and far
-- looser than the last bits of a double.
local EPS = 1e-9
local function same(a, b)
  if type(a) ~= "number" or type(b) ~= "number" then return a == b end
  local d = a - b
  if d < 0 then d = -d end
  return d <= EPS * math.max(1, math.abs(a), math.abs(b))
end

local failures, byFeature, checked = {}, {}, 0

for i = 1, #fixture.boards do
  local row = fixture.boards[i]
  local evalGrid, simGrid = gridsFrom(row.grid)
  simGrid.reveal = nil

  local plan = EvalPlan.new(simGrid, H, H)
  local got = PanelEval.allFeatures({
    board = { width = W, height = H, grid = evalGrid },
    plan = plan,
    travelFrames = row.travelFrames,
    displacement = row.displacement,
    clock = row.clock,
    earned = row.earned,
  })

  for k = 1, #fixture.features do
    local key = fixture.features[k]
    local want = row.features[key]
    if want == "Infinity" then want = math.huge end
    local have = got[key]
    checked = checked + 1
    if not same(have, want) then
      byFeature[key] = (byFeature[key] or 0) + 1
      if #failures < 20 then
        failures[#failures + 1] = string.format("  board %d  %s: lua=%s  js=%s",
          i, key, tostring(have), tostring(want))
      end
    end
  end
end

print(string.format("checked %d feature values over %d boards", checked, #fixture.boards))

if next(byFeature) == nil then
  print("PANELEVAL VERIFY OK: the Lua port agrees with the JavaScript on every board.")
  os.exit(0)
end

print("")
print("PANELEVAL VERIFY FAILED -- mismatches by feature:")
local keys = {}
for key in pairs(byFeature) do keys[#keys + 1] = key end
table.sort(keys, function(a, b) return byFeature[a] > byFeature[b] end)
for _, key in ipairs(keys) do
  print(string.format("  %-18s %4d / %d boards", key, byFeature[key], #fixture.boards))
end
print("")
print("first mismatches:")
for _, line in ipairs(failures) do print(line) end
os.exit(1)
