-- buildChipCache.lua — author the engine-verified combo catalog into recognizable chip TEMPLATES and write them to
-- bot/chipCache.lua (a plain Lua data file the live bot loads fast — no generation at runtime).
-- A template = the concrete game-color cells (the match shape) + the swap, relative to the swap anchor, as same/diff
-- color classes. FILLER (support, >=5) is don't-care (omitted). The live recognizer slides these; verify confirms.
--   luajit bot/buildChipCache.lua            -> writes bot/chipCache.lua
--   luajit bot/buildChipCache.lua 5 4 6      -> only those sizes
require("bot.headlessBoot"); do local l = require("common.lib.logger"); l.setLogLevel(l.levels.ERROR) end
_G.loc = _G.loc or function(s) return tostring(s) end
local getComboShapes = require("bot.getComboShapes")
local H, W = 12, 6

local sizes = {}
for i = 1, #arg do sizes[#sizes+1] = tonumber(arg[i]) end
if #sizes == 0 then sizes = { 5, 4 } end   -- Brian: fives and fours for now

-- engine-truth author: concrete cells (1..4) + the two swap cells, relative to (sr,sc), same/diff classes; filler omitted
local function authorCombo(g, sr, sc, kind)
  local rl, nn = {}, 0
  local function cls(col) if col == 0 then return "e" end; if not rl[col] then nn = nn + 1; rl[col] = nn end; return rl[col] end
  local incl = {}
  for r = 1, H do for c = 1, W do local v = g[r][c] or 0; if v >= 1 and v <= 4 then incl[r*100+c] = { r, c, cls(v) } end end end
  for _, cc in ipairs({ sc, sc + 1 }) do local v = g[sr][cc] or 0; local key = sr*100+cc
    if not incl[key] then if v == 0 then incl[key] = { sr, cc, "e" } elseif v <= 4 then incl[key] = { sr, cc, cls(v) } end end end
  local t = {}; for _, e in pairs(incl) do t[#t+1] = { e[1]-sr, e[2]-sc, e[3] } end
  table.sort(t, function(a, b) if a[1] ~= b[1] then return a[1] < b[1] end return a[2] < b[2] end)
  return { tmpl = t, kind = kind, swap = { 0, 0 } }
end

local function quote(v) return type(v) == "string" and ('"' .. v .. '"') or tostring(v) end
local function serTmpl(t)
  local parts = {}
  for _, e in ipairs(t) do parts[#parts+1] = string.format("{%d,%d,%s}", e[1], e[2], quote(e[3])) end
  return "{" .. table.concat(parts, ",") .. "}"
end

local out, total = {}, 0
for _, n in ipairs(sizes) do
  local raw = getComboShapes.enumerate(n).raw
  for _, rec in ipairs(raw) do
    local chip = authorCombo(rec.sample, rec.sr, rec.sc, "COMBO_" .. n)
    out[#out+1] = string.format("  { kind=%q, swap={0,0}, tmpl=%s },", chip.kind, serTmpl(chip.tmpl))
    total = total + 1
  end
  io.stderr:write(string.format("COMBO_%d: %d templates\n", n, #raw))
end

local f = assert(io.open("bot/chipCache.lua", "w"))
f:write("-- AUTOGENERATED by bot/buildChipCache.lua — engine-verified combo chip templates. DO NOT EDIT BY HAND.\n")
f:write("-- Each = { kind, swap, tmpl={{dr,dc,class}..} }. class: int=same/diff color, \"e\"=empty. Filler is don't-care.\n")
f:write("return {\n")
f:write(table.concat(out, "\n"))
f:write("\n}\n")
f:close()
io.stderr:write(string.format("wrote bot/chipCache.lua: %d templates\n", total))
