-- chips.lua — the chip cache (V2). A CHIP is a guaranteed play: "recognize a spot -> make a move -> it WORKS."
-- Brian's 100% bar: a chip that isn't 100% must not be used. Pattern-alone plateaus at ~81% (a flat snapshot can't
-- capture fall/support), so we guarantee 100% the robust way: RECOGNIZE (cheap pattern slide to narrow candidates) +
-- VERIFY (one-step sim that the move actually fires HERE). Only verified plays are returned -> 100% by construction.
-- All recognition is from the cursor outward, sliding minimal templates; junk around a template's cells is don't-care.
local BoardSim = require("bot.BoardSim")

local chips = {}
local STORE = {}            -- list of { tmpl = {{dr,dc,class}..}, kind, swaps = {{dr,dc}..} } (swaps anchor-relative)

-- ---- recognition: slide a minimal template; only its cells must satisfy the same/diff color-classes ----
-- class: an integer N = "same color across cells sharing N, different from other N"; "e" = empty(0); "g" = GARBAGE.
local function fits(grid, rows, t, R, C)
  local seen = {}
  for _, e in ipairs(t) do
    local rr, cc = R + e[1], C + e[2]
    local col = (rr >= 1 and rr <= rows and cc >= 1 and cc <= 6 and grid[rr] and (grid[rr][cc] or 0)) or -1
    if e[3] == "g" then if col ~= BoardSim.GARBAGE then return false end
    elseif e[3] == "e" then if col ~= 0 then return false end
    else
      if col <= 0 or col == BoardSim.GARBAGE then return false end
      if seen[e[3]] == nil then for _, v in pairs(seen) do if v == col then return false end end seen[e[3]] = col
      elseif seen[e[3]] ~= col then return false end
    end
  end
  return true
end

-- recognize a NAMED/SIZED chip from the store: slide every STORE chip of `kind` over the candidate cells (already
-- cursor-ordered by the caller); on a template fit, map its swap offsets to absolute cells and VERIFY the whole
-- sequence fires (caller's real-engine check) before returning. A chip carries `swaps` (a list of anchor-relative
-- offsets); a single-swap chip is just a 1-element list. Legacy `swap` (one pair) is still accepted. No BoardSim, no
-- prediction -- fits is a pure pattern-match, verify is engine-truth. nil = none here.
function chips.recognize(grid, rows, cells, kind, verify)
  for _, cell in ipairs(cells) do local R, C = cell[1], cell[2]
    for _, chip in ipairs(STORE) do
      if chip.kind == kind and fits(grid, rows, chip.tmpl, R, C) then
        local offsets = chip.swaps or { chip.swap }       -- back-compat: a single `swap` is a 1-element list
        local seq, ok = {}, true
        for _, off in ipairs(offsets) do
          local sr, sc = R + off[1], C + off[2]
          if not (sr >= 1 and sr <= rows and sc >= 1 and sc <= 5) then ok = false; break end
          seq[#seq + 1] = { sr, sc }
        end
        if ok and (not verify or verify(seq, kind)) then
          return { swaps = seq, kind = kind }
        end
      end
    end
  end
  return nil
end

-- load the autogenerated engine-verified combo templates (bot/chipCache.lua, built by buildChipCache.lua) into the
-- store. Safe if the file is absent. Auto-runs on require so the vocabulary is live without a build step.
function chips.loadCache()
  local ok, data = pcall(require, "bot.chipCache")
  if not ok or type(data) ~= "table" then return 0 end
  local n = 0
  for _, c in ipairs(data) do STORE[#STORE + 1] = { tmpl = c.tmpl, kind = c.kind, swaps = c.swaps or { c.swap or { 0, 0 } } }; n = n + 1 end
  return n
end
chips.loadCache()

return chips
